const MAX_SESSIONS = 1000;
const ANTS_PER_SESSION = 4882812n;
const ANET_CONVERSION = 100000000n;

const SESSION_DURATION_HOURS = 6;
const GRACE_PERIOD_HOURS = 2;

const OTP_EXPIRY_MINUTES = 5;
const OTP_MAX_ATTEMPTS = 5;

module.exports = {
  MAX_SESSIONS,
  ANTS_PER_SESSION,
  ANET_CONVERSION,
  SESSION_DURATION_HOURS,
  GRACE_PERIOD_HOURS,
  OTP_EXPIRY_MINUTES,
  OTP_MAX_ATTEMPTS,
};
